### ISSUE TITLE
font set family not work

### ISSUE THREAD

**Issue by BenDerPan** [NorthwoodsSoftware/GoDiagram#2]
When I  changed some State Chart Demo data value into chinese, the display text become none readable.
![image](https://user-images.githubusercontent.com/10903567/229270866-6266ec12-3ba7-4068-bd82-12fb1ed12100.png)

when i set font family in code, not work too. only support english now ?
![image](https://user-images.githubusercontent.com/10903567/229270921-57eadd9c-60ec-4feb-8050-419f47ee18cb.png)

**Comment by jonchardy** [comment]
Is the font you've specified a font that supports those characters you're trying to display? As an example, see the "Family Tree (Japanese)" sample. It includes the MS UI Gothic font, which supports Japanese characters.

**Comment by BenDerPan** [comment]
thx, works now!
