### ISSUE TITLE
Avalonia 11.0.0 preview6

### ISSUE THREAD

**Issue by joeuge** [NorthwoodsSoftware/GoDiagram#3]
Are there any plans to release version for Avalonia 11.0.0 preview 6
Thanks!

**Comment by jonchardy** [comment]
We're looking into it. There seem to be a number of breaking changes in previews 5 and 6.

**Comment by joeuge** [comment]
That's it. Looking forward to.
Thanks for your reply

**Comment by jonchardy** [comment]
We've just realeased GoDiagram for Avalonia 10.0.0-preview4, which coincides with Avalonia 11.0.0-preview6.
