### ISSUE TITLE
licensing with CI like github actions

### ISSUE THREAD

**Issue by jeacott1** [NorthwoodsSoftware/GoDiagram#4]
Hi,
 I'm somewhat confused as to how to setup a container based CI build (like github actions) for GoDiagram.
How should I properly provide the license so that builds works sans watermark? Build containers are always different.
I'm currently using GoDiagram 4 - do I have any way to do this?

**Comment by jonchardy** [comment]
I don't know that such old versions are compatible with CI. After all, version 4 released in 2011.

You may have better luck if you upgrade to version 6, which is still in support, and uses a different licensing scheme where the license key can just be inserted into source code.

**Comment by jeacott1** [comment]
@jonchardy is there any option for GoWin?

**Comment by WalterNorthwoods** [comment]
Yes, upgrade to version 6.
